#!/bin/bash

# You could treat these user keys as OTP, delete them after use
user=$(aws iam get-user | grep -Po '"UserName": *\K"[^"]*"' | tr -d '"')
accesskey=$(aws iam list-access-keys --user-name $user | grep -Po '"AccessKeyId": *\K"[^"]*"' | tr -d '"')

echo -n "removing user access key: "
echo $accesskey
aws iam delete-access-key --access-key $accesskey --user-name $user